# Generated by Django 3.2.8 on 2021-10-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(default='<django.db.models.fields.AutoField>_first_name', max_length=127)),
                ('lastName', models.TextField(default='<django.db.models.fields.AutoField>_last_name', max_length=127)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('T', 'Tank'), ('H', 'Healer'), ('M', 'Melee'), ('R', 'Ranger'), ('C', 'Caster')], default='M', max_length=2)),
                ('name', models.TextField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.role')),
            ],
        ),
    ]
